---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  commands:
  - apt-get update && apt-get install tmate -y
  - bash build.sh
  - tmate -F

